name: faal
description: Tienda virtual llevada al siguiente nivel

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  # Firebase FMC
  firebase_core: ^1.17.1
  firebase_messaging: ^11.4.1

  # State Management
  get: ^4.6.5

  # Utilitis
  flutter_svg: ^1.1.0
  flutter_barcode_scanner: ^2.0.0
  qr_flutter: ^4.0.0
  geolocator: ^9.0.1
  geocoding: ^2.0.4
  google_maps_flutter: ^2.1.8
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.2.3+1
  smooth_page_indicator: ^1.0.0+2
  shared_preferences: ^2.0.15
  animate_do: ^2.1.0
  image_picker: ^0.8.5+3
  device_info_plus: ^4.0.0
  confetti: ^0.7.0
  camera: ^0.9.8+1


  # Connections
  http: ^0.13.4
  dio: ^4.0.6

  # Payments
  mercadopago_sdk: ^1.3.0
  mercadopago_transparent: ^1.0.1
  flutter_credit_card: ^3.0.1


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/iconApp.png"

flutter_native_splash:
  color: "#FFFFFF"  
  image: "assets/iconsplash.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Barlow
      fonts:
        - asset: fonts/Barlow-Medium.ttf
          weight: 500
        - asset: fonts/Barlow-Regular.ttf
          weight: 400
          style: normal
        - asset: fonts/Barlow-SemiBold.ttf
          weight: 600
          style: normal
          
  
    - family: Inter
      fonts:
        - asset: fonts/static/Inter-Medium.ttf
          weight: 500
        - asset: fonts/static/Inter-Regular.ttf
          weight: 400
          style: normal
        - asset: fonts/static/Inter-SemiBold.ttf
          weight: 600
          style: normal
        - asset: fonts/static/Inter-ExtraBold.ttf
          weight: 800
          style: normal
        - asset: fonts/static/Inter-Bold.ttf
          weight: 700
          style: normal