name: faal
description: Tienda virtual llevada al siguiente nivel

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  # Firebase FMC
  firebase_core: ^1.17.1
  firebase_messaging: ^11.4.1

  # State Management
  get: ^4.6.5

  # Utilitis
  flutter_svg: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
